### ISSUE TITLE
Add exchange of ICE candidates

### ISSUE THREAD

**Issue by fabricedesre** [mozilla-services/remote-worker-server#8]
Exchanging sdp offer and answer is not enough to set up a connection. Both parties also need to exchange ICE candidates.
The message format could be something like:
{"messageType":"ice","action":"client-candidate","candidate":{"candidate":"candidate:2 1 UDP 2122187007 10.252.27.213 41683 typ host","sdpMid":"","sdpMLineIndex":0}}

These candidates can be sent multiple times so we need to wait for the server to confirm the data channel connection before shutting down the client web socket.

**Comment by Natim** [comment]
In order to close this we need to test the following scenarii:

 - [ ] Make sure client can start sending ICE before Gecko WebRTCAnswer
 - [ ] Make sure client can continue to send ICE after the Gecko WebRTCAnswer until {connected}
 - [ ] Make sure Gecko can send ICE after its WebRTCAnswer until connected.

**Comment by Natim** [comment]
Fixed in #10
